// Generated by CoffeeScript 1.12.5
(function() {
  var http, server;

  http = require('http');

  server = http.createServer((function(_this) {
    return function(req, res) {
      res.writeHead(200, {
        'Content-Type': 'text/plain'
      });
      return res.end('Hello Vole World!');
    };
  })(this));

  server.listen(process.env.PORT);

}).call(this);
